"""add score_notes and remove reports

Revision ID: 2d3fea27a632
Revises: 4f3b1e9c9a2a
Create Date: 2026-07-16 09:55:37.809157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2d3fea27a632'
down_revision: Union[str, None] = '4f3b1e9c9a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_report_id', table_name='reports', if_exists=True)
    op.execute('DROP TABLE IF EXISTS reports')
    # op.add_column('sessions', sa.Column('score_notes', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'score_notes')
    op.create_table('reports',
    sa.Column('report_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('report_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('download_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_hash_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('report_id', name='reports_pkey')
    )
    op.create_index('ix_reports_report_id', 'reports', ['report_id'], unique=False)
    # ### end Alembic commands ###
