"""Add AuditLog

Revision ID: 354d1e8cf214
Revises: 0001_initial_tables
Create Date: 2026-06-20 20:20:22.983966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354d1e8cf214'
down_revision: Union[str, None] = '0001_initial_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_index('idx_alerts_id', table_name='alerts')
    op.drop_index('idx_alerts_session_id', table_name='alerts')
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_session_id'), 'alerts', ['session_id'], unique=False)
    op.drop_index('idx_media_files_id', table_name='media_files')
    op.drop_index('idx_media_files_session_id', table_name='media_files')
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_index(op.f('ix_media_files_session_id'), 'media_files', ['session_id'], unique=False)
    op.drop_index('idx_refresh_tokens_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.drop_index('idx_sessions_id', table_name='sessions')
    op.drop_index('idx_sessions_patient_code', table_name='sessions')
    op.drop_index('idx_sessions_professional_id', table_name='sessions')
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_patient_code'), 'sessions', ['patient_code'], unique=False)
    op.create_index(op.f('ix_sessions_professional_id'), 'sessions', ['professional_id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_id', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_id', 'users', ['id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_sessions_professional_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_patient_code'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.create_index('idx_sessions_professional_id', 'sessions', ['professional_id'], unique=False)
    op.create_index('idx_sessions_patient_code', 'sessions', ['patient_code'], unique=False)
    op.create_index('idx_sessions_id', 'sessions', ['id'], unique=False)
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('idx_refresh_tokens_id', 'refresh_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_media_files_session_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.create_index('idx_media_files_session_id', 'media_files', ['session_id'], unique=False)
    op.create_index('idx_media_files_id', 'media_files', ['id'], unique=False)
    op.drop_index(op.f('ix_alerts_session_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.create_index('idx_alerts_session_id', 'alerts', ['session_id'], unique=False)
    op.create_index('idx_alerts_id', 'alerts', ['id'], unique=False)
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
