"""Add analysis models

Revision ID: 3a343aa1ac1b
Revises: 354d1e8cf214
Create Date: 2026-07-14 00:37:37.391286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3a343aa1ac1b'
down_revision: Union[str, None] = '354d1e8cf214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_audio', sa.String(length=512), nullable=False),
    sa.Column('transcricao', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('anxiety_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('trauma_indicator_score', sa.Float(), nullable=True),
    sa.Column('analise_comprehend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eventos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_analysis_id'), 'audio_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_audio_analysis_session_id'), 'audio_analysis', ['session_id'], unique=False)
    op.create_table('document_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_documento', sa.String(length=512), nullable=False),
    sa.Column('tipo_documento', sa.String(length=128), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('entidades_detectadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_risk_score', sa.Float(), nullable=True),
    sa.Column('psychological_risk_score', sa.Float(), nullable=True),
    sa.Column('pregnancy_risk_score', sa.Float(), nullable=True),
    sa.Column('fatores_identificados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_analysis_id'), 'document_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_document_analysis_session_id'), 'document_analysis', ['session_id'], unique=False)
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_history_id'), 'risk_history', ['id'], unique=False)
    op.create_index(op.f('ix_risk_history_patient_code'), 'risk_history', ['patient_code'], unique=False)
    op.create_index(op.f('ix_risk_history_session_id'), 'risk_history', ['session_id'], unique=False)
    op.create_table('video_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_video', sa.String(length=512), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('modelo_utilizado', sa.String(length=128), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('body_language_score', sa.Float(), nullable=True),
    sa.Column('interaction_score', sa.Float(), nullable=True),
    sa.Column('violence_indicator_score', sa.Float(), nullable=True),
    sa.Column('eventos_detectados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('resultado_final', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_analysis_id'), 'video_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_video_analysis_session_id'), 'video_analysis', ['session_id'], unique=False)
    
    # --- DATA MIGRATION (ETAPA 7) ---
    op.execute("""
        INSERT INTO risk_history (patient_code, session_id, score, nivel)
        SELECT patient_code, id, iga_score, COALESCE(iga_level, 'MEDIUM') 
        FROM sessions 
        WHERE iga_score IS NOT NULL
    """)
    op.execute("""
        INSERT INTO video_analysis (session_id, arquivo_video, emotion_score)
        SELECT id, 'migrated_video.mp4', score_video 
        FROM sessions 
        WHERE score_video IS NOT NULL
    """)
    op.execute("""
        INSERT INTO audio_analysis (session_id, arquivo_audio, anxiety_score)
        SELECT id, 'migrated_audio.mp3', score_audio 
        FROM sessions 
        WHERE score_audio IS NOT NULL
    """)
    op.execute("""
        INSERT INTO document_analysis (session_id, arquivo_documento, clinical_risk_score)
        SELECT id, 'migrated_document.pdf', score_document 
        FROM sessions 
        WHERE score_document IS NOT NULL
    """)
    # --- END DATA MIGRATION ---
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_analysis_session_id'), table_name='video_analysis')
    op.drop_index(op.f('ix_video_analysis_id'), table_name='video_analysis')
    op.drop_table('video_analysis')
    op.drop_index(op.f('ix_risk_history_session_id'), table_name='risk_history')
    op.drop_index(op.f('ix_risk_history_patient_code'), table_name='risk_history')
    op.drop_index(op.f('ix_risk_history_id'), table_name='risk_history')
    op.drop_table('risk_history')
    op.drop_index(op.f('ix_document_analysis_session_id'), table_name='document_analysis')
    op.drop_index(op.f('ix_document_analysis_id'), table_name='document_analysis')
    op.drop_table('document_analysis')
    op.drop_index(op.f('ix_audio_analysis_session_id'), table_name='audio_analysis')
    op.drop_index(op.f('ix_audio_analysis_id'), table_name='audio_analysis')
    op.drop_table('audio_analysis')
    # ### end Alembic commands ###
