"""Add participant models

Revision ID: 852f5caee90e
Revises: 2d3fea27a632
Create Date: 2026-07-17 15:23:23.843199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852f5caee90e'
down_revision: Union[str, None] = '2d3fea27a632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('body_language', sa.String(length=128), nullable=True),
    sa.Column('speech', sa.Text(), nullable=True),
    sa.Column('alert_level', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_events_event_type'), 'participant_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_participant_events_id'), 'participant_events', ['id'], unique=False)
    op.create_index(op.f('ix_participant_events_participant_id'), 'participant_events', ['participant_id'], unique=False)
    op.create_table('participant_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('face_id', sa.String(length=64), nullable=True),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('interaction_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_objects_id'), 'participant_objects', ['id'], unique=False)
    op.create_index(op.f('ix_participant_objects_object_name'), 'participant_objects', ['object_name'], unique=False)
    op.create_index(op.f('ix_participant_objects_participant_id'), 'participant_objects', ['participant_id'], unique=False)
    op.create_index(op.f('ix_participant_objects_video_id'), 'participant_objects', ['video_id'], unique=False)
    op.create_table('video_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=64), nullable=False),
    sa.Column('face_id', sa.String(length=64), nullable=True),
    sa.Column('speaker_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_frame', sa.Integer(), nullable=True),
    sa.Column('last_frame', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_participants_id'), 'video_participants', ['id'], unique=False)
    op.create_index(op.f('ix_video_participants_participant_id'), 'video_participants', ['participant_id'], unique=False)
    op.create_index(op.f('ix_video_participants_role'), 'video_participants', ['role'], unique=False)
    op.create_index(op.f('ix_video_participants_video_id'), 'video_participants', ['video_id'], unique=False)
    op.drop_index('ix_reports_report_id', table_name='reports')
    op.drop_table('reports')
    op.add_column('alerts', sa.Column('participant_id', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('role', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('related_object', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_alerts_participant_id'), 'alerts', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_participant_id'), table_name='alerts')
    op.drop_column('alerts', 'related_object')
    op.drop_column('alerts', 'confidence')
    op.drop_column('alerts', 'role')
    op.drop_column('alerts', 'participant_id')
    op.create_table('reports',
    sa.Column('report_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('report_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('download_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_hash_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('report_id', name='reports_pkey')
    )
    op.create_index('ix_reports_report_id', 'reports', ['report_id'], unique=False)
    op.drop_index(op.f('ix_video_participants_video_id'), table_name='video_participants')
    op.drop_index(op.f('ix_video_participants_role'), table_name='video_participants')
    op.drop_index(op.f('ix_video_participants_participant_id'), table_name='video_participants')
    op.drop_index(op.f('ix_video_participants_id'), table_name='video_participants')
    op.drop_table('video_participants')
    op.drop_index(op.f('ix_participant_objects_video_id'), table_name='participant_objects')
    op.drop_index(op.f('ix_participant_objects_participant_id'), table_name='participant_objects')
    op.drop_index(op.f('ix_participant_objects_object_name'), table_name='participant_objects')
    op.drop_index(op.f('ix_participant_objects_id'), table_name='participant_objects')
    op.drop_table('participant_objects')
    op.drop_index(op.f('ix_participant_events_participant_id'), table_name='participant_events')
    op.drop_index(op.f('ix_participant_events_id'), table_name='participant_events')
    op.drop_index(op.f('ix_participant_events_event_type'), table_name='participant_events')
    op.drop_table('participant_events')
    # ### end Alembic commands ###
