"""add_is_dismissed

Revision ID: e8cabed9172c
Revises: 3a343aa1ac1b
Create Date: 2026-07-14 17:52:38.993035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cabed9172c'
down_revision: Union[str, None] = '3a343aa1ac1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('alerts', sa.Column('dismissed_by', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['dismissed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'dismissed_at')
    op.drop_column('alerts', 'dismissed_by')
    op.drop_column('alerts', 'is_dismissed')
    # ### end Alembic commands ###
